### ISSUE TITLE
Syntax revision for next release: reduce user-specified keys

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram#165]
With a relatively simple syntax change I think we can make the stylesheet easier to learn and give the library more room to grow in the future!

There's a pattern in several parts of the stylesheet where the "keys" of a map are user-specified values, like this example from the docs: 
```yaml
layers:
    landuse:
        data: { source: osm }
        filter: ...
        draw: ...
        sublayer:
            filter: ...
            draw: ...
        sublayer2:
            filter: ...
            draw: ...
```
This is a nice example of the brevity enabled by YAML, but (as we probably know) there are two issues with this pattern:

1. There is implicit knowledge about which keys have built-in meaning. It's not obvious that `sublayer` doesn't have some special semantics, for instance, and in general one needs to have read the documentation for every field in order to determine if its name is meaningful. 

2. We can't add keywords to any sections using this pattern without potentially breaking existing stylesheets. In the `landuse` section here, we have locked ourselves out of adding any new properties at this level. 

An alternative:
```yaml
layers:
    - name: landuse
      data: { source: osm }
      filter: ...
      draw: ...
      layers:
          - name: sublayer
            filter: ...
            draw: ...
          - name: sublayer2
            filter: ...
            draw: ...
```
The "sequence" syntax generally creates less indentation and, while there is slightly more text, it can actually be *more* readable because it makes semantics more explicit. And of course if users aren't specifying the names of fields, there's no concern that those names will collide in the future. 

This would be a breaking change for existing stylesheets, but I am optimistic that our total future adoption can greatly outnumber the current users, so we should plan to make the best experience we can for those future users!

PS Not sure if this belongs in "issues" but I wasn't sure where else to put it
