### ISSUE TITLE
Example of multiple sources with single layers

### ISSUE THREAD

**Issue by juliomalegria** [tangrams/tangram#185]
Hey guys,

First of all, awesome work! I was on the "Mapzen SF Happy Hour Demo Time" at Code for America last week and saw all the cool stuff that Tangrams can do. Needless to say, I was very impressed! I love the clean yaml syntax.

I'm thinking about start working on an open source project that combines a lot of things: Django, GeoDjango, TileStache, and hopefully Tangram (fingers crossed).

I was going over the documentation and couldn't find an example of a styling "scene file" that uses multiple sources with single layers instead of one single source with multiple layers.

So for instance, instead of having this URL:

```
//domain.com/all/{z}/{x}/{y}.geojson
```

That returns this:

```
{
   "earth": {
      "type":"FeatureCollection",
      "features": [...],
      ...
   },
   "landuse": {
      "type":"FeatureCollection",
      "features": [...],
      ...
   }
}
```

I would have several of these URLs:

```
//domain.com/earth/{z}/{x}/{y}.geojson
//domain.com/landuse/{z}/{x}/{y}.geojson
...
```

Where each of them return something like this:

```
{
  "type":"FeatureCollection",
  "features": [...],
  ...
}
```

How would my `scene.yaml` look like for this setup, if I would like to get the same result as [this scene file (simple-demo)](https://github.com/tangrams/simple-demo/blob/gh-pages/scene.yaml)? I'm sure there is an example somewhere there and I totally missed it.

Thanks, and keep the good work!

**Comment by bcamper** [comment]
Hi @juliomalegria, thanks for writing and glad you are interested in using Tangram!

You definitely can create a scene with multiple sources as single layers (or mix sources that each have multiple layers). Looks like we need to add more examples for this. In the meantime, I've made this example:

https://gist.github.com/bcamper/6b7d85003a652c0018d6

It pulls in 3 different sources, all from Mapzen's vector tile service (which allows you to request individual layers in addition to `all`):

```
sources:
    earth:
        type: TopoJSON
        url:  //vector.mapzen.com/osm/earth/{z}/{x}/{y}.topojson
        
    landuse:
        type: TopoJSON
        url:  //vector.mapzen.com/osm/landuse/{z}/{x}/{y}.topojson

    roads:
        type: TopoJSON
        url:  //vector.mapzen.com/osm/roads/{z}/{x}/{y}.topojson
```

The rest of the file shows how to reference those for drawing. (I did these with `TopoJSON` sources but `GeoJSON` will work just the same.) Behind the scenes, Tangram will look at the response to see if it's a single `FeatureCollection`, or an object containing multiple collections.

The only caveat here is that this example is doing 3x the number of HTTP requests vs. using `all`. Of course, if that's the only way the data is accessible (say it's pulled from two different organizations with different servers) then this is probably the only way to do it. On the other hand, if it's easy to bundle the data into a single request, it will be more efficient. Either works though.

Let us know if you have more questions and please send along any examples once you get it working :)
