### ISSUE TITLE
How to display non-osm geojson tiles

### ISSUE THREAD

**Issue by hasan9206** [tangrams/tangram#246]
I am using `TileStache`  to serve `GeoJSON` vector tiles using my own data (stored in `Postgres`).

I want to use tangram to display the tiles, but I'm not sure how to go about doing this, the example uses `TopoJSON` osm tiles which are different than what `TileStache` is serving. 

Is it possible to do this? and is there a guide I can follow?

**Comment by bcamper** [comment]
Hi @hasan9206 -- you can simply use the `GeoJSON` type when configuring your data source. Our [documentation](https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/sources.md#type) has some examples, such as:

```
sources:
    tiles:
        type: GeoJSON
        url: http://tileserver.com/tiles/{z}/{x}/{y}.json
```

Let us know if you have further issues.
