### ISSUE TITLE
Check handling of nested rasters datasource

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram#296]
Example Style sheet:

```
sources:
    stamen-watercolor:
        type: Raster
        url: http://tile.stamen.com/watercolor/{z}/{x}/{y}.jpg
    stamen-toner:
        type: Raster
        url: http://tile.stamen.com/toner/{z}/{x}/{y}.png
        rasters: [stamen-watercolor] # add watercolor sampler alongside toner
    test-source:
        type: Raster
        url: blah
        rasters: [stamen-toner]
```

This should be same as doing:

```
sources:
    stamen-watercolor:
        type: Raster
        url: http://tile.stamen.com/watercolor/{z}/{x}/{y}.jpg
    stamen-toner:
        type: Raster
        url: http://tile.stamen.com/toner/{z}/{x}/{y}.png
    test-source:
        type: Raster
        url: blah
        rasters: [stamen-toner, stamen-watercolor]
```
