### ISSUE TITLE
Freezing while editing shader involving premature EOF syntax error

### ISSUE THREAD

**Issue by louh** [tangrams/tangram#311]
@karimnaaji just found a bug in Tangram. This was originally filed here https://github.com/tangrams/tangram-play/issues/349 (in Tangram Play), but in narrowing down the root cause we've determined the problem to lie in Tangram itself.

> A shader being inject with a premature end of file sometimes freezes tangram-play for unknown reason.

> To test this, add a style with any shader injection point, start a multi line comment /* without its enclosing */. The shader injected results in incomplete shader (thus the premature EOF syntax error) and makes tangram-play to freeze.

Some additional observations:

- The shader must be used. An unclosed multi-line comment in a shader block is fine if the style is never used elsewhere (in the example below, try renaming `buildings` to `buildings1`.
- The `styles` block must be somewhere in the middle of the document. An unclosed multi-line comment at the end of a scene file is fine.

Here is a full YAML that will break Tangram:

```yaml
cameras:
    perspective:
        type: perspective
        vanishing_point: [0, -500]

lights:
    directional1:
        type: directional
        direction: [.1, .5, -1]
        diffuse: .7
        ambient: .5

styles:
    buildings:
        base: polygons
        shaders:
            blocks:
                color: |
                    color.rgb *= vec3(min((worldPosition().z*.001 + .5),1.));
                    /* vec2 var0;















                    vec2 var1;
sources:
    mapzen:
        type: TopoJSON
        url: https://vector.mapzen.com/osm/all/{z}/{x}/{y}.topojson

layers:
    water:
        data: { source: mapzen }
        draw:
            polygons:
                order: 2
                color: '#353535'

    earth:
        data: { source: mapzen }
        draw:
            polygons:
                order: 0
                color: '#555'

    landuse:
        data: { source: mapzen }
        draw:
            polygons:
                order: 1
                color: '#666'

    roads:
        data: { source: mapzen }
        filter: { not: { kind: ferry } }
        draw:
            lines:
                order: 2
                color: '#777'
                width: 5
        labels:
            filter: { name: true }
            highway:
                filter: { kind: highway, $zoom: { min: 7 } }
                draw:
                    text:
                        font:
                            family: Helvetica
                            fill: white
                            size: 12px
                            weight: bold
            not_highway:
                filter: { not: { kind: highway }, $zoom: { min: 13 } }
                draw:
                    text:
                        font:
                            family: Helvetica
                            fill: white
                            size: 11px

    buildings:
        data: { source: mapzen }
        filter: { $zoom: { min: 14 } }
        draw:
            polygons:
                order: 50
                color: '#999'
        extruded:
            filter: { $zoom: { min: 15 } }
            draw:
                polygons:
                    style: buildings
                    extrude: function () { return feature.height > 0 || $zoom >= 16; }
```
