### ISSUE TITLE
focal_length dependent on canvas height?

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#317]
seeing what appears to be focal_length changes depending on canvas height:

![building-scale2](https://cloud.githubusercontent.com/assets/459970/15579564/2554cf50-2333-11e6-926a-f3e38ed66ed6.gif)

Is this the defined behavior?

Seeing it with this scene file (does the same thing without the `vanishing_point` param in there, but it's harder to see what's going on):

```
    sources:
        shapes:
            type: GeoJSON
            url: ../esb.geojson
    cameras:
        camera1:
            type: perspective
            vanishing_point: [-50, -150]
    lights:
        light1:
            type: point
            origin: ground
            position: [0, -250, 250]
    layers:
        buildings:
            data: { source: shapes }
            draw:
                polygons:
                    order: 1
                    color: [1, 1, 1]
                    extrude: true
```
