### ISSUE TITLE
Reduce code duplication in style files

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram#320]
This is feature suggestion.

In any style.yaml for tangram, I read _a lot_ of these things:

``` yaml
                    # limit show smaller landuse areas to higher zooms
                    - { $zoom: { min: 4 },  area: { min: 1000000000 } }
                    - { $zoom: { min: 5 },  area: { min: 1000000000 } }
                    - { $zoom: { min: 6 },  area: { min: 150000000 } }
                    - { $zoom: { min: 7 },  area: { min: 100000000 } }
                    - { $zoom: { min: 8 },  area: { min: 10000000 } }
                    - { $zoom: { min: 9 },  area: { min: 5000000 } }
                    - { $zoom: { min: 10 }, area: { min: 1000000 } }
                    - { $zoom: { min: 11 }, area: { min: 500000 } }
                    - { $zoom: { min: 12 }, area: { min: 250000 } }
                    - { $zoom: { min: 13 }, area: { min: 100000 } }
                    - { $zoom: { min: 14 }, area: { min: 50000 } }
                    - { $zoom: { min: 15 }, area: { min: 20000 } }
                    - { $zoom: { min: 15 }, area: { min: 2000 } }
                    - { $zoom: { min: 16 } }
```

...and also these things...

``` yaml
        ocean-labels-z1:
            filter: { $zoom: [1] }
            draw:
                text-blend-order: { font: { size: 8px } }
        ocean-labels-z2:
            filter: { $zoom: [2] }
            draw:
                text-blend-order: { font: { size: 10px } }
        ocean-labels-z3:
            filter: { $zoom: [3] }
            draw:
                text-blend-order: { font: { size: 13px } }
```

It looks like, that wherever $zoom is used, there is a direct correlation with the size of the feature. Even where a size/area is not explicitly given, it is implied by a expectation of a size of a feature, like here:

``` yaml
        stream:
            filter: { kind: [stream], $zoom: { max: 17 } }
```

**So my proposal is**
- _change_ the unit of size-related features from m/m² to size _on the viewport_ in cm/cm². For example, `filter: { area { min: 1, max: 25 } }` would match all areas whose size on the screen is between 1cm² and 25cm². So, this implicitly includes the zoom. 
- define metadata that specifies the (assumed) size/width of non-polygon features like streams, rivers, shopping malls etc and make it accessible in the style. Something like this: `filter: { kind: [water-line], width {min: 0.2 } }` would match all waterways whose width or assumed width in meters (if none is given) would be at least 2mm on the map at the current scale.

**Pros of this approach**
- The metadata of the importance/assumed size of features is not defined in each style again and again, every time a little different -> no duplication of this metadata
- _a lot_ less code duplication when deciding when to display a feature, how prominent to display a feature and when to show a label or not
- seamless zooming in the sense that the map also renders i.e. zoom 14.5 and 14.0 differently is possible (Not sure if it feels good, but it is at least possible).
- the necessity to group the areas into "importance" tiers (which is also part of the metadata that is currently in the style) is probably unnecessary then. This also removes _a lot_ of boilerplate
- style file would pretty much shrink into defining what features to display at all and how to color/texturize them, I think

**Cons of this approach**
- Because the units would be changed, suddenly, all styles would be invalid and would have to be fixed.
