### ISSUE TITLE
texture creation fails after import during material redefinition

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#339]
**To reproduce:** create two files, `import.yaml` and `style.yaml`.

In `import.yaml` specify a style like so:

```yaml
styles:
    test-style:
        base: polygons
        material:
            diffuse: .75
```

in `style.yaml`, override the diffuse parameter with a texture, like so:

```yaml
styles:
    test-style:
        material:
            diffuse:
                texture: sofa.png
```

**Result:**
The scene will fail to load, with:

> Scene.load() failed to load http://localhost:8080/unit-tests/materials/materials-texture.yaml: Cannot create property 'texture' on number '0.75' TypeError: Cannot create property 'texture' on number '0.75'(…)

**Expected result:**
The material definition specified in `style.yaml` will override the initial `diffuse` setting and use the texture rather than the `.75` setting.
