### ISSUE TITLE
Using new v0.8.2 release of Tangram breaks scene reload

### ISSUE THREAD

**Issue by sensescape** [tangrams/tangram#356]
Seems like v0.8.2 release of Tangram has a bug. When I reset to v0.8.1 I don't experience this.

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- Checkout Tron style locally: https://github.com/tangrams/tron
- Load it using `http-server --cors -p 8000`
- Load localhost:8000 in Chrome
- Zoom into SF interchange at http://localhost:8000/#17/37.73599/-122.40648
- Change some stuff in the `roads.yaml` 

e.g. Set the colors to orange and green as below.

```
                lines-highway-z17-dark:
                    order: 38
                    #order: function () { return (feature.sort_key * 10 + 5); }
                    style: lines
                    color: orange #[0.086,0.135,0.260]
                    width: [[8,0px],[16,0px],[17,12px],[18,15px]]
                lines-highway-z17-casing-light:
                    order: 36
                    #order: function () { return (feature.sort_key * 10 + 4); }
                    style: lines
                    color: green #[0.541,0.969,0.949]
                    width: [[8,0px],[16,0px],[17,15px],[18,18px]]
```

**RESULT:**

The map rendering should have updated to show orange and green roads.

**EXPECTED RESULT:**

No update to the map, instead they show the old blue colors.

**ENVIRONMENT:**

- Mac.
- Chrome Version 51.0.2704.103 (64-bit)

**OTHER:**

**Workaround.** Close all Chrome windows, then make a new Chrome window loading the same URL (http://localhost:8000/#17/37.73599/-122.40648) and it'll draw fine. Loading a new Incognito Window while the original window is still open shows the bug. All Chrome windows with Tangram need to be closed.
