### ISSUE TITLE
filter interpretation question

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#363]
Looking at https://github.com/tangrams/zinc-style/blob/gh-pages/zinc-style.yaml#L4054-L4066 : what is going on with this filter?

```yaml
neighborhood-z11:
    filter:
        all:
            - name: true
            - kind: [macrohood, neighbourhood]
            - $zoom: [11]
        any:
            - source: [openstreetmap, openstreetmap.org]
            - source: [whosonfirst, whosonfirst.mapzen.com]
              all:
                - min_zoom: [11]
                - max_zoom: { min: 12 }
                - is_landuse_aoi: false
```

As I understand from https://mapzen.com/documentation/tangram/Filters-Overview/#lists-imply-any-mappings-imply-all : because the first "all" and "any" layers are in the form of a mapping, the filter will match if the feature matches every condition in the first "all" block AND at least one of the conditions in the first "any" block – so far, so good.

But what is that second "all" doing under the "any"? How does that indent work under the two "source" list entries? Does it count as one of the entries in the "any" list? I've tested it in Play and it seem to function as a requirement equivalent to the outer-most "all", but I'm not sure.

**Comment by blair1618** [comment]
In a "block style" YAML sequence, e.g. 
```yaml
- first: 1
  second: 2
- third: 3
```
Each `-` denotes the start of a new mapping (or "object"). The YAML above is exactly equivalent to:
```yaml
- { first: 1, second: 2 }
- third: 3
```

In the context above, the `source` and `all` entries under the `any` together form one mapping.
