### ISSUE TITLE
Notes on dash implementation

### ISSUE THREAD

**Issue by pnorman** [tangrams/tangram#393]
I've been implementing styling for railways and have a few issues or oddities that I came across and noted down. After triage some of these might be inherent in the Tangram design or best solved in a different repo (e.g. documentation), but I thought the notes from someone experienced in other styling languages but not Tangram were worth keeping together.

![image](https://cloud.githubusercontent.com/assets/1190866/17888598/8ecae832-68e0-11e6-945b-8fcc01c1e792.png)
1. I couldn't find any examples of dashes in any of the demos. cinnabar defines a `dashedline` style with a [bunch of javascript](v3.0.0). A railway style like I'm doing is fairly standard and I'm surprised there aren't any I could find in the demo styles.
2. With the dash size and background colour being defined in the style while the width and colour are defined in the layer's draw, there's a split between where similar styling information is defined. This split makes maintenance and changes harder.
3. Transitioning between a solid line and a dashed line with casing is difficult.
   
   I tried something like this for the layers
   
   ``` yaml
   train:
   filter:
     - class: rail
       $zoom: {min: 5}
     - class: narrow_gauge
       $zoom: {min: 6}
   draw:
     flatlines:
       order: 600
       color: &rail-outer-color '#888'
       width: function () { return 0.06*Math.exp(0.33*$zoom) * 156250*Math.exp(-$zoom*0.69) }
   hz-train:
     filter:
       - class: [rail, narrow_gauge]
         $zoom: {min: 10}
     draw:
       dashed-line:
         order: 600
         color: black
         width: 10
         outline:
           color: red
           width: function () { return 2 * 156250*Math.exp(-$zoom*0.69) }
   ```
   
   I did something similar earlier with highways, but it didn't work here, probably because `lines` and `dashed-line` are different. Instead I had to do
   
   ``` yaml
   train:
   filter:
     - class: rail
       $zoom: {min: 5, max: 10}
     - class: narrow_gauge
       $zoom: {min: 6, max: 10}
   draw:
     flatlines:
       order: 600
       color: &rail-outer-color '#888'
       width: function () { return 0.06*Math.exp(0.33*$zoom) * 156250*Math.exp(-$zoom*0.69) }
   hz-train:
   filter:
     - class: [rail, narrow_gauge]
       $zoom: {min: 10}
   draw:
     dashed-line:
       order: 600
       color: black
       width: 10
       outline:
         color: red
         width: function () { return 2 * 156250*Math.exp(-$zoom*0.69) }
   ```
4. Dashes with an outline are odd
   
   ![image](https://cloud.githubusercontent.com/assets/1190866/17889895/64d11a04-68e7-11e6-8da8-7fd5adaadf80.png)
   
   I can understand what's happening here. but it doesn't seem like an effect people would want. In my case I want to get a solid outline, but I could also see people wanting each dash to have an outline. I can't see anyone wanting a dash quite like this.
