### ISSUE TITLE
Position variable - YAML

### ISSUE THREAD

**Issue by Asjad27** [tangrams/tangram#400]
Hi, I am trying to use the values of "position.x" and "position.y" variables inside the YAML. I just wanted to know the format (lat/long, mercator, tile coords etc.) of the values which are contained in these variables.

![screenshot from 2016-08-30 15 40 27](https://cloud.githubusercontent.com/assets/4342016/18086202/25e6b9c0-6ec8-11e6-9dab-d97a71cb2ed2.png)

Also, is there any way to print the values of these variables?

Thank you

**Comment by bcamper** [comment]
Hi @Asjad27 -- the `position` shader variable is in *Mercator-projected meters*. It usually makes most sense to make relative modifications to it, here's an example that *shifts the buildings 10 meters to the right* (you can comment/uncomment the `position.x += 10.` line to see the difference):

```
styles:
    buildings:
        base: polygons
        shaders:
            blocks:
                position: |
                    position.x += 10.; // shift buildings 10 meters to the right
```

https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fapi.github.com%2Fgists%2Fb778a4049f4f4b3a967c4084e9676ae6&lines=13-19#17.9471/37.73953/-122.45962

Unfortunately there is no way to print anything from a WebGL shader -- one of the more difficult aspects of debugging them :) A common technique is to modify colors to indicate different values. 

Here's another example that shows a red color gradient that repeats every 100 meters:

https://mapzen.com/tangram/play/?lines=20-21&scene=https%3A%2F%2Fapi.github.com%2Fgists%2F119d57577044fbdb7aaa222ab01cfcde#17.9471/37.73953/-122.45962

Hope those help!
