### ISSUE TITLE
proposal -- map legend creation

### ISSUE THREAD

**Issue by burritojustice** [tangrams/tangram#417]
Add a `legend` parameter to allow users to specify draw elements to be used to generate a map legend.

The legend colors would based on colors and style specified by a draw element. This way, if the user changes colors and styles, the legend would update dynamically.

The user would specify a display name for the label in the `legend` parameter, which would also toggle the inclusion of that draw element in the legend

The legend itself would be drawn in GL and defined as a special legend layer, where the style of the box, text style and background are defined.

```
layers:
    borders:
        data: { source: borders}
            international_border:
                filter: { admin_level: 2 }
                draw:
                    lines:
                        color: aqua
                        width: 2px
                        order: 10
                    legend: "national border"
             regional_border:
                filter: { admin_level: 4 }
                draw: 
                    lines:
                        color: green
                        width: 2px
                        order: 20
                    legend: "regional border"
    industrial:                                
        data: { source: industrial }
        draw:
            polygons:
                color: yellow
            lines:
                color: blue
                width: 2px
            legend: "industrial area"

    capitals:                                
        data: { source: capitals }
        draw:
            points:
                color: blue
                width: 2px
            legend: "capital cities"

    legend:                                
        draw:
            lines:
                color: black
                width: 2px
            polygon:
                color: [1,1,1,0.5]
            text:
                color: black
                size: 14px
                family: Helvetica


```
