### ISSUE TITLE
proposal -- add colorbrewer palettes as a color option for points, polygons and lines

### ISSUE THREAD

**Issue by burritojustice** [tangrams/tangram#418]
add colorbrewer schemes to `color:`

```
layers:
    counties:
        polygon:
            color: OrRd[2]    
```

https://github.com/axismaps/colorbrewer/

hex is here, for reference:

https://github.com/google/palette.js/blob/master/palette.js#L931
