### ISSUE TITLE
Global variables assigned to shader uniforms are parsed as relative URLs.

### ISSUE THREAD

**Issue by louh** [tangrams/tangram#449]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

Here is a minimal test case:

```yaml
import:
    - https://tangrams.github.io/blocks/functions/zoom-full.yaml

sources:
    mapzen:
        type: TopoJSON
        url: https://tile.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.topojson

global:
    a: [1, 0, 0]
    b: [0, 0, 1]

layers: 
    earth:
        data: { source: mapzen }
        draw:
            polygons:
                order: 0
                color: grey
    water:
        data: { source: mapzen }
        draw:
            water:
                order: 1
                color: lightblue

styles:
    water:
        base: polygons
        mix: [functions-zoom]
        shaders:
            defines:
                ZOOM_START: 1
                ZOOM_END: 20
            uniforms:
                u_a: global.a
                u_b: global.b
            blocks:
                color: |
                    color.rgb = mix(u_a, u_b,zoom());
```

View in Tangram Play: https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fmapzen.com%2Fapi%2Fscenes%2F7%2F48%2Fresources%2Fscene.yaml#5.022/43.291/-65.717

I am defining colors as `global` variables and then assigning them as uniforms in the shader block at the bottom of the YAML. We expected these values to be passed along to the uniform values. We see instead that Tangram has parsed the references to `global.a` as relative URLs. When we examine the compiled `scene.config` object, we see that `scene.config.styles.water.shaders.uniforms.u_a` now equals `"https://gist.githubusercontent.com/anonymous/804452ab17846fa83732e535d73b7d87/raw/555c9626c3893ea634a7590eaa4e9813df184a95/global.a"` (and similar thing occurs for `u_b`).

Tangram's error in the console is this: 

```
Tangram v0.11.0 [error]: ERROR: 0:758: 'mix' : no matching overloaded function found 
ERROR: 0:758: 'assign' :  cannot convert from 'const float' to 'highp 3-component vector of float'
```
