### ISSUE TITLE
Problem loading Leaflet optimized GeoJSON source

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram#461]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

I taught a class at UC Berkeley recently and one of the students contacted me to debug a scene file problem. He had a GeoJSON file that works in Leaflet, but pointing Tangram at the same file failed to display the data.

See scene file snippet below.

The key part is the Leaflet optimized GeoJSON file had a Javascript object variable in the source file saying `var dataset = { "type": "FeatureCollection", "features": [ … ] }` instead of just the GeoJSON part (`{ "type": "FeatureCollection", "features": [ … ] }`). 

My work around was to saved out the data file out as a pure GeoJSON in the gist.githubusercontent.com URL below.

But it seems like we should support GeoJSON with this configuration, it'd make us interoperable with the major mapping library out there, especially since we're embedded inside Leaflet on JS now.

```
import: https://mapzen.com/carto/refill-style-no-labels/refill-style-no-labels.yaml

sources:
    _doublepark:
        type: GeoJSON
        # works as "cleaned-up" geojson
        url: https://gist.githubusercontent.com/nvkelso/cce46a3ecfc00ee2e7c600d825fe016a/raw/0c522e437402d63b2f295d978e09d5d7acb3ea4d/evan_geojson.json
        # doesn't work as original Leaflet "GeoJSON"
        #url: https://gist.githubusercontent.com/nvkelso/a0a2a184865867bee90b1e061537b3bd/raw/1e685114ddf02bf233f8a48ad07c1deb28c786a5/leaflet.geojson

layers:
    _doublepark:
        data: { source: _doublepark}
        draw:
            points:
                size: [[6,1px],[12,4px],[16,10px]]
                collide: false
                color: [1.000, 0.000, 0.000, 1.00]
```

**RESULT:**

Only the Refill basemap draws in Tangram Play, no data visualization overlay.

**EXPECTED RESULT:**

I should see red dots for each GeoJSON point feature on top of the basemap.

**ENVIRONMENT:**

Tangram Play on Mac Safari.

**OTHER:**

Love you guys!

<img width="511" alt="screen shot 2016-11-30 at 12 53 28" src="https://cloud.githubusercontent.com/assets/853051/20770869/0c332262-b6fc-11e6-9932-e76d4a442ee9.png">
