### ISSUE TITLE
Angled text hard to read

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram#475]
Loading up Cinnabar which uses v0.11 Tangram the angled road text is extremely hard to read. It's like it's missing it's aliasing? The horizontal text looks sharp. Road shield artwork is also pixelated.

http://tangrams.github.io/cinnabar-style/#13/37.7652/-122.3880

1x screen
![screen shot 2016-12-21 at 11 04 45](https://cloud.githubusercontent.com/assets/853051/21402570/f536bede-c76d-11e6-869e-57e15765db58.png)

2x screen
<img width="1125" alt="screen shot 2016-12-21 at 11 05 54" src="https://cloud.githubusercontent.com/assets/853051/21402569/f5240a6e-c76d-11e6-9e74-58e20e363c63.png">

**Comment by dmvaldman** [comment]
Perhaps scaling the texture by 200% instead of 150% would improve things? (since integer values will remain integer valued when scaled)

**Comment by dmvaldman** [comment]
May also be a font-related issue, as we are increasing the font size, then scaling it down. If the smaller-sized fonts in Cinnabar are designed uniquely for their small font size, then we will lose this finer structure.

**Comment by bcamper** [comment]
@nvkelso what browser? would be helpful to compare behavior across a few.

I think @dmvaldman's point about small fonts is relevant though, we may need special handling for fonts below a certain threshold (we may want to *not* scale those up).

In testing, we found that 200% scaling universally made things worse than 150%.

**Comment by bcamper** [comment]
I kind of feel like these fonts are just too small to render well on 1x. Here is a comparison from before and after recent diagonal text supersampling changes. Neither is great. We can experiment with some different settings based on small font size, but I am just not sure there are enough pixels to get this working well (you either get too much blurriness or too much aliasing).

Chrome:
![tpxvndo5p5rag2sxjjkwbgikz5cgqrkuz7kzhapjvnevtqhta6elef4 l0hv97 h7qvexvc4yrnaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/16733/21403573/5b2b93be-c78b-11e6-82b5-433a4e8931ba.png)

Safari:
![unknown](https://cloud.githubusercontent.com/assets/16733/21403575/5eb76882-c78b-11e6-8198-d81d36cc2045.png)

**Comment by nvkelso** [comment]
Agree on not applying it to small text labels (11 px and smaller?)

Agree some of our house style text sizes are too small. I filed a few
issues to clean that up (make the minimum size more like Bubble Wrap), such
as https://github.com/tangrams/cinnabar-style/issues/16.

**Comment by pnorman** [comment]
My impression is that the labels are harder to read than Mapnik rendered labels at the same size

z14 SF
![image](https://cloud.githubusercontent.com/assets/1190866/21410502/0cb548c8-c796-11e6-938e-214d75e583f7.png)

The font for orange and yellow roads is 9px Noto Sans. Mapnik has advantages here (server-side, not real time), but it's possible to get better results.

fwiw, osm-carto fonts are too small too

**Comment by bcamper** [comment]
I certainly can't disagree that better is possible :)  FWIW, I tried adjusting the Cinnabar colors and switching to 9px Noto Sans to get a closer comparison (still not apples to apples). Mapnik on the left, Tangram on the right. It's not the same, but it's still pretty close IMO; Tangram is still a bit more washed out.

![screen shot 2016-12-22 at 4 49 25 pm](https://cloud.githubusercontent.com/assets/16733/21441636/1313cf1a-c867-11e6-8680-b77c947b8256.png)

Here's another Tangram example with a 200% (rather than 150%) scaling factor. While I think it looks pretty good here, @meetar has pointed out that the changes in sharpness are uneven and very context-dependent, so it's unclear yet if there is either a better default, or if we can adjust these values on the fly for better results.

![screen shot 2016-12-22 at 4 50 42 pm](https://cloud.githubusercontent.com/assets/16733/21441711/80f56610-c867-11e6-8e45-2773618fdc89.png)

**Comment by nvkelso** [comment]
This has been working okay in practice. Closing.

**Comment by pnorman** [comment]
I did some analysis of labels, and was considering opening a new issue. Instead I'll add it here for future reference

This is all with Tangram 0.15 on a machine that has Noto Sans installed locally.

I have a scene file with the following (simplified)
```yaml
styles:
  labels:
    base: text
    draw:
      font:
        family: Noto Sans
        size: 14px
        fill: 'black'
        stroke:
          color: 'white'
          width: '1.75px'
layers:
  transport:
    data: { source: bolder }
    filter:
      $geometry: line
    minor:
      filter:
        class: [secondary, tertiary]
        $zoom: { min: 9 }
      draw:
        lines:
          order: 300
          color: global.freecolour.H080_L85_C050
          width: *motorway-width
          cap: round
          outline:
            color: global.freecolour.H080_L75_C060
            width: *motorway-casing-width
    minor-labels:
      filter:
        class: [secondary, tertiary]
        $zoom: { min: 10 }
      draw:
        labels:
          priority: 90
          font:
            size: 11px
            fill: black
            stroke: 
              color: white
              width: 1px
```

OpenStreetMap Carto [has the following](https://github.com/gravitystorm/openstreetmap-carto/blob/d3ebbf3298b393e0e46ad00e2b3094fcea92cdd5/roads.mss#L2849-L2874) after simplification and variable substitution

```mss
  [highway = 'secondary'] {
    [zoom >= 13] {
      text-name: "[name]";
      text-size: 8;
      text-fill: black;
      text-face-name: "Noto Sans Regular";
      text-halo-radius: 1;
      text-halo-fill: #f7fabf;
    }
    [zoom >= 14] {
      text-size: 9;
    }
    [zoom >= 15] {
      text-size: 10;
    }
    [zoom >= 17] {
      text-size: 11;
    }
    [zoom >= 19] {
      text-size: 12;
    }
  }
```

Some text using the above Tangram scene file styling is
![image](https://user-images.githubusercontent.com/1190866/38450907-d5a274b0-39da-11e8-8480-fbaf63144707.png)
4x
![image](https://user-images.githubusercontent.com/1190866/38450909-e1a22ae4-39da-11e8-9212-06eee21eab1b.png)


With the CartoCSS,
![image](https://user-images.githubusercontent.com/1190866/38450883-b1ae61c2-39da-11e8-902a-d6aa67d0a6e5.png)
4x
![image](https://user-images.githubusercontent.com/1190866/38450898-bb9ddbf4-39da-11e8-97a6-08a7b6fb7ab2.png)

I'm not sure if the Tangram output is worse or not. I think it's slightly worse, but not horribly worse, like it used to be.
