### ISSUE TITLE
Tangram doesn't understand absolute URL paths

### ISSUE THREAD

**Issue by migurski** [tangrams/tangram#477]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

Sample scene file excerpt, hosted from http://127.0.0.1:5000/scene.yaml:

```YAML
import: https://mapzen.com/carto/refill-style/4/refill-style.yaml

sources:
    _dots:
        type: GeoJSON
        url: "/{z}/{x}/{y}.json"
        max_zoom: 14
```

**RESULT:**

Tangram makes failing requests to URLs like "http://127.0.0.1:5000//12/656/1582.json" (note the double slash before the zoom level).

**EXPECTED RESULT:**

A URL starting with a slash should resolve to the root of the server, like "http://127.0.0.1:5000/12/656/1582.json".

**ENVIRONMENT:**

Tangram v0.11.6, Safari Version 9.1 (11601.5.17.1), OS X 10.11.4 (15E65). The tiles and scene file are both served with Flask, which has a `url_for()` function that produces slash-prefixed URLs.
