### ISSUE TITLE
Should MVT tiles currently work?

### ISSUE THREAD

**Issue by migurski** [tangrams/tangram#478]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

Sample scene file excerpt:

```YAML
import: https://mapzen.com/carto/refill-style/4/refill-style.yaml

sources:
    _dots:
        type: MVT
        url: "{z}/{x}/{y}.mvt"
        max_zoom: 14
```

**RESULT:**

Console log errors like:

```
Tangram v0.11.6 [warn]: tile load error(s) for _dots/15/2639/6359/14: skip@https://mapzen.com/tangram/0.11/tangram.min.js:7:8933
readFields@https://mapzen.com/tangram/0.11/tangram.min.js:7:5731
r@https://mapzen.com/tangram/0.11/tangram.min.js:8:17905
n@https://mapzen.com/tangram/0.11/tangram.min.js:8:15787
readFields@https://mapzen.com/tangram/0.11/tangram.min.js:7:5697
r@https://mapzen.com/tangram/0.11/tangram.min.js:8:15739
value@https://mapzen.com/tangram/0.11/tangram.min.js:13:30641
https://mapzen.com/tangram/0.11/tangram.min.js:13:21897
s@https://mapzen.com/tangram/0.11/tangram.min.js:2:8838
https://mapzen.com/tangram/0.11/tangram.min.js:2:8960
l@https://mapzen.com/tangram/0.11/tangram.min.js:1:31540
promiseReactionJob@[native code]
```

**EXPECTED RESULT:**

Dots matching what I’m seeing with GeoJSON tile content.

**ENVIRONMENT:**

Tangram v0.11.6, Safari Version 9.1 (11601.5.17.1), OS X 10.11.4 (15E65). The tiles are generated with Tippecanoe 1.15.1.

A sample tile response: http://mike.teczno.com/img/tangram-sample-tile-12-2637-6358.mvt

**Comment by nvkelso** [comment]
@migurski 

I'd expect something more like:

```
import: https://mapzen.com/carto/refill-style/4/refill-style.yaml

sources:
    _dots:
        type: MVT
        url: http://mike.teczno.com/img/tangram-sample-tile-{z}-{x}-{y}.mvt
        max_zoom: 14
```

or

```
import: https://mapzen.com/carto/refill-style/4/refill-style.yaml

sources:
    _dots:
        type: MVT
        url: localhost:80/path/to/tiles/{z}/{x}/{y}.mvt
        max_zoom: 14
```

And check if your tiles are MVT or GeoJSON format (the extensions and type will need to match).

**Comment by migurski** [comment]
I tried making the URL fully-qualified and got the same errors in the console:

```YAML
sources:
    _dots:
        type: MVT
        url: "http://127.0.0.1:5000/{z}/{x}/{y}.mvt"
        max_zoom: 14
```

So that didn’t help. I know that the data source works, because this is displaying dots correctly:

```YAML
sources:
    _dots:
        type: GeoJSON
        url: "{z}/{x}/{y}.json"
        max_zoom: 14
```

<img width="642" alt="screen shot 2017-01-09 at 10 01 41 pm" src="https://cloud.githubusercontent.com/assets/58730/21795508/3b1d4bb8-d6b7-11e6-9080-70e19b2895ed.png">
