### ISSUE TITLE
Polygons and polylines are rendered without an 'order' value

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram#503]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

Load this scene:
```yaml
scene:
    background:
        color: lightblue
sources:
    mapzen:
        type: TopoJSON
        url: https://tile.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.topojson
layers:
    earth:
        data:
            source: mapzen
        draw:
            polygons:
                color: grey
            lines:
                width: 2px
                color: yellow
```

**RESULT:**

Yellow polylines are drawn around grey Earth layer polygons.

**EXPECTED RESULT:**

The `lines` and `polygons` draw rules on the `earth` layer have no `order` values specified, and `order` is a required parameter for these styles, as noted in the documentation (https://mapzen.com/documentation/tangram/draw/#order), so both the yellow polylines and the grey polygons should _not_ be drawn.

**ENVIRONMENT:**

MacOS 10.11.6, Firefox 51.0.1, Tangram Play v0.5.2, Tangram v0.11.8

**OTHER:**

This differs from the current behavior of tangram-es, as noted here: https://github.com/tangrams/tangram-es/issues/1314
