### ISSUE TITLE
rendering all text labels regardless collision

### ISSUE THREAD

**Issue by michaelhornak** [tangrams/tangram#505]
Hi,
I am trying to render text labels for all points regardless of collision. From the documentation it seems it should work only by setting collision false for both points and its text. However this isnt working for me. Labels are still removed due to some collision tests and never shows all at once.

This si my code Im using in [https://mapzen.com/tangram/play/?#20.00000/37.75110/-122.43611](https://mapzen.com/tangram/play/?#20.00000/37.75110/-122.43611)

```
sources:
    mapzen:
        type: TopoJSON
        url: https://tile.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.topojson
layers:
    buildings:
        data: { source: mapzen }
        draw:
            points:
                color: red
                collide: false
                size: 5px
                text:
                    text_source: function() { return 'label' }
                    anchor: bottom
                    font:
                        fill: green
                        size: 10pt
                    collide: false
                    optional: true
```

I am pretty sure there is some rookie mistake in my style config. I would be very glad for any help. Thanks

**Comment by bcamper** [comment]
Hi -- by default, nearby labels with the same text will be culled such that they only repeat within [`repeat_distance`](https://mapzen.com/documentation/tangram/draw/#repeat_distance) pixels of each other. This often comes up with test examples like this, where the same label text ("label") is being used for every feature. You can cause all of these labels to show up by setting `repeat_distance: 0px`, like this:

```
                text:
                    text_source: function() { return 'label' }
                    repeat_distance: 0px
                    anchor: bottom
                    font:
                        fill: green
                        size: 10pt
                    collide: false
                    optional: true
```

Let us know if you have any further questions on this behavior.
