### ISSUE TITLE
Incomplete raster tile coverage with a certain WMTS service

### ISSUE THREAD

**Issue by mattrei** [tangrams/tangram#510]
Hello everybody,

thanks for your great product. I ran into some issues today:

I want to use this WMTS service in my map
https://tiles.maps.eox.at/wmts/1.0.0/WMTSCapabilities.xml

All layers have the same problem: they do not show up correctly.
For instance if it want to use the _s2cloudless_ layer by setting the url to:
`https://tiles.maps.eox.at/wmts/1.0.0/s2cloudless/default/WGS84/{z}/{y}/{x}.jpg` it omits a half of the world only (those maps show detailled terrains over Europe). 

See [my example here](https://mapzen.com/tangram/view/?scene=https://mapzen.com/api/scenes/408/317/resources/blank.yaml#3.26/62.02/176.38)

The scene file code is simply as it could be:
```
sources:
    eox:
        type: Raster
        url: https://tiles.maps.eox.at/wmts/1.0.0/s2cloudless/default/WGS84/{z}/{y}/{x}.jpg

layers:
    satellite:
        data: {source: eox}
        draw:
            raster:
                order: 0
```

See the [maps providers page](https://s2maps.eu/) for the desired results. 

Thanks for looking into it.

Best,
Matthias
