### ISSUE TITLE
view breaks if mapzen_sdk_api_key is not set

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#524]
Saved this scene in Play (with a working key):

```
sources:
    mapzen:
        type: TopoJSON
        url: https://tile.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.topojson
        url_params:
            api_key: mapzen-xxxxxxx
layers:
    buildings:
        data: { source: mapzen }
        draw:
            polygons:
                order: 0
                color: white
```

Then tried to open it in view/:

https://mapzen.com/tangram/view/?scene=https%3A%2F%2Fmapzen.com%2Fapi%2Fscenes%2F5%2F384%2Fresources%2Fblank.yaml#14.2875/34.1963/-118.6282

Map failed to draw, with console error:

```
Tangram v0.11.8 [warn]: Caught exception in listener for event 'load': TypeError: Cannot read property 'sdk_mapzen_api_key' of undefined
    at e._isApiKeyMissing (https://mapzen.com/js/mapzen.standalone.min.js:2:5734)
    at Object.load (https://mapzen.com/js/mapzen.standalone.min.js:2:5171)
    at https://mapzen.com/tangram/0.11/tangram.min.js:18:3528
    at Array.forEach (native)
    at e.trigger (https://mapzen.com/tangram/0.11/tangram.min.js:18:3472)
    at e.value (https://mapzen.com/tangram/0.11/tangram.min.js:12:23527)
    at https://mapzen.com/tangram/0.11/tangram.min.js:12:7980
```
