### ISSUE TITLE
terrain doesn't load in windows/edge or ie 

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#538]
Terrain layer does not draw in windows/edge or ie. In Walkabout or any of the terrain-demos demos the other layers and styles draw but terrain is missing.

**Comment by bcamper** [comment]
Console errors?

**Comment by meetar** [comment]
Looks like it's a shader problem with all raster tiles. Console error:

```
Tangram v0.12.1 [error]: Shader compilation errors
(0, 0): Internal compiler error
```

Test scene:

```
sources:
    normals:
        type: Raster
        url: https://tile.mapzen.com/mapzen/terrain/v1/normal/{z}/{x}/{y}.png?api_key=mapzen-xxxxxxx
layers:
    terrain:
        data: { source: normals }
        draw:
            raster:
                order: 0
```
