### ISSUE TITLE
requests on tiles when enabled set to false

### ISSUE THREAD

**Issue by michaelhornak** [tangrams/tangram#560]
Hi,

i want to ask about sending request on tiles behavior when layer option enabled is set to false. I assumed there should be no requests when every layer has enabled set to false, but I got requests on every source even if all layers a disabled and not visible in map. 

Is there a way or option that has to be set to disable sending request on tiles? Or I would need to remove completely source and layer and then recreate it again when I need to show it on map.

Thanks.

**Comment by bcamper** [comment]
Currently, tiles are requested from a given data source if there is *at least one top-level layer referencing that source* (via the `source` parameter in the  `data` block).

It shouldn't be difficult to restrict this so that tiles are omitted if `enabled: false` is set on all *top-level* layers that reference the data source.

However, if the top-level layer does not itself set `enabled: false`, we would likely not descend into all deeper layers to see if all of them are disabled (too much complexity for a relatively small savings in these cases).

For example, in the logic described above, this would **NOT** request tiles for the source names `tiles`:

```
layers:
  data: { source: tiles }
  enabled: false # disable this whole layer
```

However, the following case **WOULD** continue to request tiles for source `tiles`:

```
layers:
  data: { source: tiles }
  # enabled defaults to true, so top-level layer is enabled, but child layers may be disabled

  sublayer1:
     enabled: false
     ...
  sublayer2:
     enabled: false
     ...
```
