### ISSUE TITLE
`size` stops ignored in `style` definition defaults

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#568]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

Make a new `style` and set a `draw` default including a `size` definition as stops:

```yaml
styles:
    my_points:
        base: points
        draw:
            color: red
            size: [[13, 14px], [16, 18px], [18, 19px]]
```

**RESULT:**

Points are not drawn unless the `size` is constant, eg `32px`. Stops are only respected under a `layer` declaration.

Example scene:

https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fmapzen.com%2Fapi%2Fscenes%2F5%2F730%2Fresources%2Fblank.yaml#17.15007/37.79860/-122.41190

To test a fixed size, uncomment line 10: `size: 32px`
To test stops under a `layer`, uncomment line 19.
