### ISSUE TITLE
Feature Request: Allow draw.collide option to be a funcion

### ISSUE THREAD

**Issue by IagoLast** [tangrams/tangram#582]
While the [colide](https://mapzen.com/documentation/tangram/draw/#collide) field **must** be a static boolean field, another fields like the [color](https://mapzen.com/documentation/tangram/draw/#color) allows functions.

It would be nice to accept functions in the collide field so for example the value would change depending on the zoom level.

Does it seems like a good idea to you?

Regards.

**Comment by bcamper** [comment]
Hi @IagoLast -- for most cases where we allow a JS function, the output value can be a continuous range that is likely to vary significantly according to feature properties (e.g. feature property mapped to a color range). For fields like `collide` that can only accept a boolean, where each value gives very different behavior, the currently preferred way would be to use separate sub-layers with a `filter` to differentiate your features. This is more efficient for the engine to evaluate, as there is some overhead to the JS functions (checking a simple boolean vs. having to call an additional function for every feature, and in addition this has a higher bar for our native ES codebase than in a browser environment). If you have a use case where you think this doesn't make sense, please feel free to elaborate.

**Comment by IagoLast** [comment]
Hi @bcamper thx for the quick reply.

We are generating the `scene.yaml` using a [turbocarto](https://github.com/CartoDB/turbo-carto) file (think in a `css` for maps).

So for example, this map will have green points in small cities and red points in big ones.

```less
#cities_layer {
  marker-with: 20px;
  [population <= 1000000] {
    marker-color: green;
  }
  [population > 1000000] {
    marker-color: red;
  }
}
```

Generates the following `scene.yaml`

```yaml
layers:
...
    cities_layer:
        data:
            ...
        draw:
            points_0d78ba88223feb7bb63e1ead1bc7d169:
                size: 20
                color: "function() { if (feature['population'] <= 1000000) {return 'green"} else { return 'red'}}"
```

This runs perfectly, but when we do something similar but varying the `collide` field it doesn't work.


Im not acquainted with sub-layers. Do you think that using them can solve this kind of issues?

Regards.

**Comment by bcamper** [comment]
You can nest layers (to any depth), and each sub-layer narrows the filter of the layer above it (like a more specific CSS selector). The `draw` properties from the ancestor layers inherit. See the [layer docs](https://mapzen.com/documentation/tangram/Filters-Overview/) for more info.

So in your example something like this, with a new sub-layer to change the `collide` value based on a feature property called `capital` for capital cities (this is a hypothetical example):

```
layers:
...
    cities_layer:
        data:
            ...
        draw:
            points_0d78ba88223feb7bb63e1ead1bc7d169:
                size: 20
                color: "function() { if (feature['population'] <= 1000000) {return 'green"} else { return 'red'}}"
                collide: true # turn collision on by default

        # turn collision off for capital cities only
        capital-cities:
            filter: function() { return feature.capital; }
            draw:
                points_0d78ba88223feb7bb63e1ead1bc7d169:
                    collide: false
```
