### ISSUE TITLE
Docs: outline for polygons

### ISSUE THREAD

**Issue by dv343** [tangrams/tangram#585]
I was reading https://mapzen.com/documentation/tangram/draw/#outline , and it says that `outline` can only be used for lines and points.

However, there is a reference here (https://mapzen.com/documentation/tangram/draw/#stroke) that mention `outline` for polygons.

Could you clarify the support for outlines with polygons?

Thank you!

**Comment by bcamper** [comment]
Ah, the reference to `outline` in the context of polygons is incorrect (we had direct support for that a long time ago but no longer).

The way to draw an outline for a polygon is to create two `draw` blocks:

```
draw:
   # draw polygon fill
   polygons:
      ...
   # draw polygon outline
   lines:
      width: 1px
```
