### ISSUE TITLE
add in-browser linting to catch Tangram syntax errors

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#604]
As per https://github.com/tangrams/tangram/issues/603, malformed Tangram syntax fails silently with no console feedback.

Example:
```yaml
scene:
  background: 'hsl(204, 39%, 95%)'
```
This scene file has no effect, as the syntax is incorrect, and should be:
```yaml
scene:
  background:
    color: 'hsl(204, 39%, 95%)'
```
Some kind of Tangram-specific linting which throws console errors would be very helpful.
