### ISSUE TITLE
516px elevation tiles designed to overlap shrink to fit tilesize of 512 showing seams  in Tangram Play

### ISSUE THREAD

**Issue by Codefalter** [tangrams/tangram#607]
**TANGRAM VERSION:**

0.13.4

**ENVIRONMENT:**

Windows 10 Pro
Chrome 61.0.3163.100 (64bit)
Tangram Play

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- Add the 516px elevation tiles as source
```
mapzen_elevation:
  type: Raster
  url: https://tile.mapzen.com/mapzen/terrain/v1/516/terrarium/{z}/{x}/{y}.png
  url_params:
    api_key: global.sdk_mapzen_api_key
  tile_size: 512
  max_zoom: 14
```

- Sampling the elevation data with currentRasterPixel and sampleRasterAtPixel

Sample .yaml file (api_key removed):
[sample516elevation.zip](https://github.com/tangrams/tangram/files/1372028/sample516elevation.zip)

**RESULT:**

The tiles don't line up and show seams. It basicaly shrinks the 516x516 down to 512x512.

**EXPECTED RESULT:**

Perfect alignement of tiles and no seams. Sampling at pixel `(0, 0)` should sample the texel `(2, 2)` on a 516px texture.
```
(-2, -2) -> (0, 0)
(512, 512) -> (514, 514)
```

Maybe set by a source parameter `overlap: 2` or guessed as the ` tile_size` is set to `512` but the tile is actually `516`
