### ISSUE TITLE
Is it possible to use .mbtiles file as map source directly.

### ISSUE THREAD

**Issue by gimkim** [tangrams/tangram#628]
Is it possible for tangram javascript to directly use the vector .mbtiles file as map source without a tile server??
I tried with mbtiles file from openmaptiles.com but no luck.

Something like this
```
sources:
    mapzen:
        type: TopoJSON
        url: file:///D:/localweb/test.mbtiles
        tile_size: 256
        max_zoom: 15
```
