### ISSUE TITLE
`auto` should apply if no sprites set

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#642]
**TANGRAM VERSION:**

0.15.1

**ENVIRONMENT:**

macOS 10.13.4, Chrome 66 & Firefox

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**
Using a 64px image, I used this scene file:
```yaml
sources:
    tilezen:
        type: TopoJSON
        url: https://tile.nextzen.org/tilezen/vector/v1/512/all/{z}/{x}/{y}.topojson
textures:
    icons:
        url: mapzen.png
layers:
    mypois:
        data: { source: tilezen, layer: pois }
        draw:
            points:
                texture: icons
                size: [16px, auto]
```
**RESULT:**

The points were drawn 64px x 64px.

**EXPECTED RESULT:**

Expected 16px x 16px. If I use a sprite, the ratio works:

```yaml
sources:
    tilezen:
        type: TopoJSON
        url: https://tile.nextzen.org/tilezen/vector/v1/512/all/{z}/{x}/{y}.topojson
textures:
    icons:
        url: images/mapzen.png
        sprites:
            thesprite: [0, 0, 64, 64]
layers:
    mypois:
        data: { source: tilezen, layer: pois }
        draw:
            points:
                texture: icons
                sprite: thesprite
                size: [16px, auto]
```
