### ISSUE TITLE
% sizes should apply when no sprites set

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#644]
Same as https://github.com/tangrams/tangram/issues/642 but for a `size` using a %:

```yaml
sources:
    tilezen:
        type: TopoJSON
        url: https://tile.nextzen.org/tilezen/vector/v1/512/all/{z}/{x}/{y}.topojson
textures:
    icons:
        url: mapzen.png
layers:
    mypois:
        data: { source: tilezen, layer: pois }
        draw:
            points:
                texture: icons
                size: 50%
```
