### ISSUE TITLE
using sprite documentation

### ISSUE THREAD

**Issue by guyisra** [tangrams/tangram#658]
the docs refer the sprites sporadically and I couldn't find a complete example of having an imported zip (what structure should it be?) and accessing the sprites with it. Also (perhaps due to lack of my understanding) do sprites need to always be on styles or can they be used inline in the layer `draw`?

Did I miss the page of it somehow?

**Comment by meetar** [comment]
@guyisra Thanks for the feedback! Information on sprites is scattered around a bit, and can certainly be improved :)

The summary is: Sprites are defined as part of a `texture` definition, and then referenced in a points-based `draw` block. Normally the texture would be associated with a layer as part of a `styles` definition as you mention, but with JS only, you can reference the texture directly in the draw block, which would look like this:

```
textures:
    pois:
        url: sprites.png
        sprites:
            airport: [0, 0, 32, 32]
            restaurant: [0, 777, 32, 32]

layers:
    airports:
        data: { source: datasource }
        draw:
            points:
                texture: pois
                sprite: airport            
```

This is documented here, though it doesn't have an example about sprites at the moment: https://github.com/tangrams/tangram-docs/blob/master/docs/Syntax-Reference/draw.md#texture

Importing a zip should behave the same as instantiated a Leaflet layer with one, as documented here: https://github.com/tangrams/tangram-docs/blob/master/docs/Overviews/Tangram-Overview.md#scene-bundling

So assuming that all of the assets used for your map (such as your scene file and any images) are all in a directory with each other, and that the scene file references these assets with relative paths, you can bundle the scene file and all of the assets together into a zip, and then import that into another scene file. Tangram will unzip that bundle into a temporary directory, and then relative paths will resolve the same as before they were zipped. So assuming you use relative paths, you don't need to treat sprites any differently if the texture files are going into a zip.
