### ISSUE TITLE
Multiple labels per polygon in (MVT)

### ISSUE THREAD

**Issue by sk1me** [tangrams/tangram#663]
**TANGRAM VERSION:**
15.1

**ENVIRONMENT:**
All OS and Browsers

**RESULT:**

I have problem with Mapzen's TangramJS labelling. I am using MVT tiles and labels as an attributes to polygons that are multiplying in large scales. Below an example:

![image](https://user-images.githubusercontent.com/35774692/44341024-04a0fe00-a487-11e8-8646-5e7c29711cdb.png)

I would like to put one label per feature. I've tried also an idea from https://mapzen.com/blog/tangram-labels/ It seems to work only for TopoJSON and GeoJSON tiles - not for  MVT.

Do you have any idea how to resolve this problem for Mapbox Vector Tiles?

**EXPECTED RESULT:**

One label per polygon in MVT format.

**Comment by meetar** [comment]
Hi @sk1me, thanks for the report – what datasources are you using? And are you able to post your scene file anywhere?

**Comment by sk1me** [comment]
I'm using my own data source tiles generated by software based on arcgis server (I can't give an address - company policy....). Anyway it's in format like: http://..../tile/vector/{z}/{y}/{x}.mvt

Another example:
![image](https://user-images.githubusercontent.com/35774692/44383572-6f9b1500-a519-11e8-972e-ef000de06e9f.png)

Chunk of the YAML file:

```
sources:
    BDOT:
        type: MVT
        tile_size: 512
        min_zoom: 6
        max_zoom: 18
        generate_label_centroids: true
        url: http://.../vector/{z}/{y}/{x}.mvt
		
layers:
 OT_PTWP_A_join:
    data:
      layer: OT_PTWP_A_join_Dis
      source: BDOT
    filter: function() {return /Ps/.test(feature.rodzaj) && $zoom >= 6;}
    draw: 
      jeziorapolygons:
        color: [0.678, 0.867, 0.992, 1.00]
        interactive: true
        order: 44
      jezioraetykietypoligony:
        filter:
            label_placement: true
        anchor: center
        order: 44
        offset: [1px,-1]
        move_into_tile: false
        buffer: 50px
        priority: 1
        repeat_distance: 2500px
        collide: true
        text_source: function() {return feature.nazwa_zbiornika;}
        text_wrap: true
        font:
            family: Arial
            fill: [0.271, 0.545, 0.725, 1.00]
            anchor: center
            size: 10px
            style: italic
            weight: bold
            stroke: { color: [0.651, 0.882, 1.000, 0.30], width: 2px }
			
styles:
    jeziorapolygons:
      base: polygons
      blend_order: 69.22
      blend: overlay
    jezioraetykietypoligony:
      base: text
      blend_order: 100
      blend: overlay
```

Maybe the labels are on other tiles? Anyway I would like only one label (like for point).

**Comment by bcamper** [comment]
I don't know if this is your issue, but your second `filter` needs to go *outside* the `draw` block, in a separate layer:

```
layers:
 OT_PTWP_A_join:
    data:
      layer: OT_PTWP_A_join_Dis
      source: BDOT
    filter: function() {return /Ps/.test(feature.rodzaj) && $zoom >= 6;}
    draw: 
      jeziorapolygons:
         ...
      jezioraetykietypoligony:
        filter:
            label_placement: true
            ...
```

should be something like:

```
layers:
 OT_PTWP_A_join:
    data:
      layer: OT_PTWP_A_join_Dis
      source: BDOT
    filter: function() {return /Ps/.test(feature.rodzaj) && $zoom >= 6;}
    draw: 
     jeziorapolygons:
       ...

    labels:
        filter:
            label_placement: true
        draw:
          jeziorapolygons:
          ...
```

**Comment by nvkelso** [comment]
If it's MVT tiles versus GeoJSON file won't `generate_label_centroids: true` in the source blog generate a label per tile part, and since more than one tile is in view then I'd expect there to be "duplicate" labels for that feature on screen.

If you only want one label for feature across multiple tiles you'd need to generate the centroid for the feature server-side and export that as a separate feature.

```
sources:
    BDOT:
        type: MVT
        tile_size: 512
        min_zoom: 6
        max_zoom: 18
        generate_label_centroids: true
```

**Comment by sk1me** [comment]
After suggestion of @bcamper I did a change like this:
```
sources:
    BDOT:
        type: MVT
        tile_size: 512
        min_zoom: 6
        max_zoom: 18
        generate_label_centroids: true
        url: http://.../vector/{z}/{y}/{x}.mvt
		
layers:
#jeziora
 OT_PTWP_A_join:
    data:
      layer: OT_PTWP_A_join_Dis
      source: BDOT
    Jeziora:
      filter: function() {return /Ps/.test(feature.rodzaj) && $zoom >= 6;}
      draw: 
        jeziorapolygons:
            color: [0.678, 0.867, 0.992, 1.00]
            interactive: true
            order: 44
#jeziora labels
    Jeziora_labels:
      filter: function() {return /Ps/.test(feature.rodzaj) && $zoom >= 6;}
      draw:
        jezioralabels:
            anchor: center
            order: 44
            offset: [1px,-1]
            move_into_tile: false
            buffer: 50px
            priority: 1
            repeat_distance: 2000px
            collide: true
            text_source: function() {return feature.nazwa_zbiornika;}
            text_wrap: true
            font:
                family: Arial
                fill: [0.271, 0.545, 0.725, 1.00]
                anchor: center
                size: 10px
                style: italic
                weight: bold
                stroke: { color: [0.651, 0.882, 1.000, 0.30], width: 2px }

styles:
    jeziorapolygons:
      base: polygons
      blend_order: 69.22
      blend: overlay
    jezioralabels:
      base: text
      blend_order: 100
      blend: overlay
```

And now repeat distance parameter started to work as I think. It looks better, I'm quite happy with an effect, for now it is not multiplying labels (lakes labels):

![image](https://user-images.githubusercontent.com/35774692/44452302-777cb700-a5f6-11e8-9e96-dd02c63b2fad.png)

And in the bigger scale:
![image](https://user-images.githubusercontent.com/35774692/44452920-12c25c00-a5f8-11e8-9548-7281fcb20165.png)

I think that's the solve for only one label:

@nvkelso 
> If you only want one label for feature across multiple tiles you'd need to generate the centroid for the feature server-side and export that as a separate feature.

I've thought of a workaround:
Generate centroids of polygons (in GIS software), save them as a points and upload to the database as a separate feature.
