### ISSUE TITLE
shader program not compiling correctly

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#665]
**TANGRAM VERSION:**

0.15.3

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

Use this scene:

```
sources:
    terrain:
        type: Raster
        url: https://tile.nextzen.org/tilezen/terrain/v1/512/normal/{z}/{x}/{y}.png

layers:
    landuse:
        data: { source: terrain, layer: _default }
        draw:
            raster:
                order: 1
```

And then move the cursor over the map.

**RESULT:**

The map draws, but as soon as the cursor touches the map, an error is thrown:

```
tile.js:587 Uncaught TypeError: Cannot read property 'uniform' of undefined
    at Tile.setupProgram (tile.js:587)
    at View.setupTile (view.js:316)
    at scene.js:652
    at Array.forEach (<anonymous>)
    at _loop3 (scene.js:637)
    at _loop2 (scene.js:621)
    at Scene.renderStyle (scene.js:620)
    at Scene.renderPass (scene.js:587)
    at Scene.render (scene.js:512)
    at Scene.update (scene.js:471)
```

**OTHER NOTES:**

Triggering `scene.update()` via the console does not result in the error.
