### ISSUE TITLE
Specular lighting not working as expected

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram#680]
I am trying to create hillshading like is in OpenTopoMap - https://www.opentopomap.org
in hypsometric mode (it is used only up to zoom 8). As you can see it has some slight specular, I am trying to create this effect in Tangram style, but unfortunately without a success. Here are lights I have in style:

```
specular_light:
    type: directional
    direction: [-1.0, 1.0, -1.0]
    diffuse: 0.0
    ambient: 0.0
    specular: 1.0
ambient_light:
    direction: [1, -1, -.01]
    type: directional
    diffuse: 1.0
    ambient: 1.0
```

and here is material for style:

```
material:
    diffuse: 0.5
    ambient: 0.5
    specular: 1.0
    shininess: 0.5
```

unfortunately it results only half of the screen to be actually affected by specular. I have tried several numbers to set in camera's direction, but without a luck. Here is an image of the result:

![specular](https://user-images.githubusercontent.com/2378743/47237761-54953600-d3e0-11e8-9ac6-33d48973525e.jpg)

Could I ask you for help, or some hints of what I am doing wrong? Thank you a lot.
