### ISSUE TITLE
SVG manipultaion via scene.yaml

### ISSUE THREAD

**Issue by Tonidor** [tangrams/tangram#727]
I'm currently trying to manipulate the color of some POI icons (SVG) and I need them to change whatever is not white. Is it possible to target a specific fill component via the tangrams draw/color property?

This is a part of my scene.yaml of the layer I wish to change:
```
    layers:
        containers:
            data: {source: containers}
            draw:
                container:
                    order: function() { return feature.sort_rank; }
                    priority: 2
                    size: global.feature_size
                    color: global.get_color
                     interactive: true
```

This is the funtion getColor that is referenced above:
```
  get_color: |
    function () {
    var b= {'r':1,'g':0,'b':0}
    var a= {'r':0,'g':1,'b':0}
    var total = 0;
    for(var idx in feature.pins.questions){
                var question = feature.pins.questions[idx]
                if (question.hasOwnProperty("answers"))  {
                    total += question.answers.length;
                    }
        }
    
total = total <= 0? 0 : total >= 100 ? 100 : total;

    var t = total / 100;
    var color= [a.r + (b.r - a.r) * t,
            a.g + (b.g - a.g) * t,
            a.b + (b.b - a.b) * t]
    return color;
    }
```

Icon style:
```
<style>
 .cls-1{isolation:isolate;}.cls-2{opacity:0.6;mix-blend-mode:multiply;}.cls-3{fill:#fff;}.cls4{fill:#37474f;}
</style>
```

This is how it look's so far:
![image](https://user-images.githubusercontent.com/35833464/62533685-93995880-b847-11e9-939a-75b1dabeba67.png)
