### ISSUE TITLE
Rotate texture in shader according to underlaying geometry

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram#728]
Hello, I am trying to accomplish texture rotation in Tangram according to geometry rotation as is done in Mapnik, for example this is OpenTopoMap styling for pitch texture:

![otm](https://user-images.githubusercontent.com/2378743/66314485-62570a80-e914-11e9-87bb-8e6a04998412.png)

I am trying to achieve this in Tangram style, but I am not sure whether it is possible to rotate texture based on geometry orientation (in this case landuse polygon) and then render it correctly in Shader. Currently I only get this:

![topo](https://user-images.githubusercontent.com/2378743/66314614-97fbf380-e914-11e9-82e4-ff26ab2fa8da.png)

This is styling I use:

```
texture-scale-pitch:
    base: polygons
    blend: overlay
    blend_order: -1
    texcoords: true
    shaders:
        uniforms:
            u_customtexture: images/otm-symbols-modified/sports-soccer.svg
        blocks:
            color: |
                color = texture2D(u_customtexture, v_texcoord);
```

Is it possible in Tangram styling to achieve what can be achieved in Mapnik?
