### ISSUE TITLE
stange source.bounds behavior

### ISSUE THREAD

**Issue by Zaitsev** [tangrams/tangram#746]
**TANGRAM VERSION:**

0.20

_If you're not using the latest version, please try that first before filing an issue!_

- _Latest version:_ https://mapzen.com/tangram/tangram.min.js
- _Notes for latest version:_ https://github.com/tangrams/tangram/releases/latest

**ENVIRONMENT:**

https://play.tangram.city/?#4.167/57.429/1.644

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**
```yaml
sources:
    nextzen:
        type: TopoJSON
        url: https://tile.nextzen.org/tilezen/vector/v1/all/{z}/{x}/{y}.topojson
        bounds: [4.6917305, 52.6455735, 4.7323208, 52.6613424]
layers:
    water:
        data: { source: nextzen }
        draw:
            polygons:
                order: 2
                color: '#353535'
    earth:
        data: { source: nextzen }
        draw:
            polygons:
                order: 1
                color: '#555555'
```
**RESULT:**

clipping rectangle "jumpy" not consistent with coordinates, its scaling etc

I'd tested it with bounds from documentation `bounds:  [-74.1274, 40.5780, -73.8004, 40.8253]` with the same errors

![tngr](https://user-images.githubusercontent.com/127843/73449002-dd807880-436a-11ea-944f-434a1ef1baa3.gif)

**EXPECTED RESULT:**

it should clipp map by given bounds coordinates
