### ISSUE TITLE
outlines are not extruded with their lines

### ISSUE THREAD

**Issue by burritojustice** [tangrams/tangram#749]
**TANGRAM VERSION:**

0.20.1

**ENVIRONMENT:**

Chrome / Safari

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

extrude lines that have an `outline`

```
  _xyz_lines:
    draw:
      xyz_text:
        visible: true
      xyz_lines:
        extrude: |
            function(){return feature.last_edited_date.slice(-4)*10}
        offset: |
            function(){if (feature.dir == 'E'){return -5}; if (feature.dir == 'N'){return -5}}
        width: 4px
        outline:
          width: 1px
          color:
            - 0.5
            - 0.5
            - 0.5
            - 0.5
```

https://burritojustice.github.io/xyz-maps/bike_lanes/

**RESULT:**

lines are extruded, outlines are not

**EXPECTED RESULT:**

outlines should be extruded with their lines
