### ISSUE TITLE
untiled datasource from object

### ISSUE THREAD

**Issue by Zaitsev** [tangrams/tangram#754]
**TANGRAM VERSION:**

latest

Is it possible to add  untiled datasource not from file but from JS object etc:
```yaml
sources:
    overlay:
        type: GeoJSON
        url: |
               function(){return some_on_the_fly_geojson()}

```
