### ISSUE TITLE
Overlapping polygons at tile edges, using jawg.io tiles

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram#759]
**TANGRAM VERSION:** 0.20.1
**ENVIRONMENT:** Firefox 77.0.1, Windows 10

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- Go to https://play.tangram.city/?#15.2500/51.8805/10.4567
- In Tangram Play, open https://raw.githubusercontent.com/ENT8R/streetcomplete-mapstyle/jawg/streetcomplete-light-style.yaml
- The style uses jawg.io as tile source. Add `api_key: Zv2Mm3fkkjfqjWQ7bZ8xradVnzJv8ZlRBqtSYkZoNuBRhcpB5n8l58aU6YYGvfYB` to the globals. (This is a temporary token that will be revoked when this bug is closed). The map should render (almost fine) now

**RESULT:**

![image](https://user-images.githubusercontent.com/4661658/84603988-29076f00-ae93-11ea-9d2e-ea9544da4d9b.png)

**EXPECTED RESULT:**

The same, but without the overlapping polygons at the tile edges.
I figured that as tiles can not overlap, it can't be a problem of the tiles. They also render fine with mapbox, as shown here: https://www.jawg.io/en/maps/#13.66/51.87577/10.46222

**STYLE USED**

This should be the relevant section of the used stylesheet (in `land.yaml`):
```
layers:
    hillshade:
        data: { source: jawg , layer: hillshade }
        highlights:
            filter: { highlight: true }
            draw:
                hillshade-light-style:
                    order: 100
                    color: '#040404'
        shadows:
            filter: { shadow: true }
            draw:
                hillshade-shadow-style:
                    order: 100
                    color: '#f9f9f9'

styles:
    hillshade-light-style:
        base: polygons
        blend: add
    hillshade-shadow-style:
        base: polygons
        blend: multiply
```
