### ISSUE TITLE
Using dash with function() does not work

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram#794]
**TANGRAM VERSION:** 0.21.1

**ENVIRONMENT:** Firefox 98.0.2, Windows 11

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

Copy and paste this style
```yaml
sources:
    jawg:
        type: MVT
        url: https://tile.jawg.io/streets-v2/{z}/{x}/{y}.pbf
        max_zoom: 16
        url_params:
            access-token: Rqx0Qqc3TAHCG5MVXmxSAkaSgwm5nVSq4fV8IeTxiq9cieOQFfOt5BsYjK8Cwkqr

layers:
    road:
        data: { source: jawg }
        filter: { class: [main] }
        draw:
            lines:
                order: 1
                color: "#fff"
                width: 16m
                dash: [1,1] # function() { return [1,1] }
```
into https://play.tangram.city/?#14.4750/40.7252/-73.9982

You should see something like this

![image](https://user-images.githubusercontent.com/4661658/160488382-d746ddc2-d22b-4e1a-9a12-d5b88958a058.png)

Now, replace the `[1,1]` behind `dash:` with the commented out part.

**RESULT:**

play.tangram.city freezes, the map is not rendered.

**EXPECTED RESULT:**

The map is rendered exactly the same as before
