### ISSUE TITLE
Duplicate labels on polygons

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram#801]
**TANGRAM VERSION:**

0.21.1

**ENVIRONMENT:**

Win10, Firefox

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

Copy&Paste this style into https://play.tangram.city/?#20.00000/53.59579/9.94521

```yaml
sources:
    jawg:
        type: MVT
        url: https://tile.jawg.io/streets-v2/{z}/{x}/{y}.pbf
        max_zoom: 16
        url_params:
            access-token: Rqx0Qqc3TAHCG5MVXmxSAkaSgwm5nVSq4fV8IeTxiq9cieOQFfOt5BsYjK8Cwkqr

layers:
    buildings:
        data: { source: jawg, layer: building }
        draw:
            polygons:
                order: 100
                color: "#999"
    anything:
        data: { source: jawg, layer: building }
        draw:
            text:
                text_source: function() { return "✕" }
                priority: 1
                collide: false
                font:
                    fill: "#f00"
                    size: 26px
                    weight: bold
```

**RESULT:**

You'll see this:

![image](https://user-images.githubusercontent.com/4661658/190410872-f4208be3-1de7-4761-a4c9-4ddde25f242a.png)

There is an extra duplicate label not at the centroid but at the first node of the polygon.

This does not happen for all polygons with labels, only for some.

Tangram-ES has an identical issue.

**EXPECTED RESULT:**

For polygons, there is only one label.

**ADDITIONAL INFORMATION:**

This is neither a problem with the OSM data, see: https://www.openstreetmap.org/way/612211229#map=19/53.59555/9.94558

Nor an issue with jawg.io data, see
![image](https://user-images.githubusercontent.com/4661658/190411399-4f1e843a-7c8c-4992-82c9-e5fcd3aeaf43.png)
https://www.jawg.io/docs/apidocs/maps/streets-v2/#19.89/53.5957094/9.9453778
